import type { Client, Project, Finding, Vulnerability } from './types';

export const clients: Client[] = [
  { id: 'cli-1', name: 'Innovatech Solutions', contact: 'contact@innovatech.com', logoUrl: 'client-logo-1', language: 'en' },
  { id: 'cli-2', name: 'Quantum Dynamics', contact: 'security@quantum.com', logoUrl: 'client-logo-2', language: 'en' },
  { id: 'cli-3', name: 'SecureBank Corp', contact: 'audit@securebank.com', logoUrl: 'client-logo-3', language: 'es' },
  { id: 'cli-4', name: 'HealthFirst Providers', contact: 'compliance@healthfirst.com', logoUrl: 'client-logo-4', language: 'en' },
];

export const projects: Project[] = [
  { id: 'proj-1', clientId: 'cli-1', name: 'Q3 Web App Pentest', scope: '*.innovatech.com', startDate: '2023-07-01', endDate: '2023-07-15', status: 'Completed' },
  { id: 'proj-2', clientId: 'cli-2', name: 'API Security Audit', scope: 'api.quantum.com', startDate: '2023-08-10', endDate: '2023-08-25', status: 'Completed' },
  { id: 'proj-3', clientId: 'cli-3', name: 'Auditoría Red Interna', scope: '10.0.0.0/8', startDate: '2023-09-01', endDate: '2023-09-30', status: 'In Progress' },
  { id: 'proj-4', clientId: 'cli-1', name: 'Mobile App Assessment', scope: 'Innovatech iOS App', startDate: '2023-10-05', endDate: '2023-10-20', status: 'In Progress' },
];

export const findings: Finding[] = [
  {
    id: 'find-1',
    projectId: 'proj-1',
    vulnerabilityId: 'vuln-001',
    title: 'SQL Injection in Login Form',
    severity: 'Critical',
    cvss: 9.8,
    markdown: `### Description\n\nThe login form at /login is vulnerable to SQL injection. By providing a crafted payload in the username field, an attacker can bypass authentication.\n\n### Evidence\n\nPayload: \`' OR 1=1 -- \`\n\n### Mitigation\n\nUse parameterized queries.`,
    createdAt: '2023-07-05',
    updatedAt: '2023-07-06',
  },
  {
    id: 'find-2',
    projectId: 'proj-1',
    vulnerabilityId: 'vuln-002',
    title: 'Cross-Site Scripting (XSS) in Search Results',
    severity: 'High',
    cvss: 8.8,
    markdown: `### Description\n\nThe search functionality is vulnerable to reflected XSS. Malicious scripts can be injected via the search query parameter.\n\n### Evidence\n\nURL: \`/search?q=<script>alert('XSS')</script>\`\n\n### Mitigation\n\nEncode output and validate input.`,
    createdAt: '2023-07-08',
    updatedAt: '2023-07-08',
  },
  {
    id: 'find-3',
    projectId: 'proj-3',
    title: 'Exposición de servicio SMB sin protección',
    severity: 'Medium',
    cvss: 6.5,
    markdown: `### Descripción\n\nSe ha identificado un servicio SMB en la red interna que permite el acceso anónimo, exponiendo archivos sensibles de la compañía.\n\n### Evidencia\n\n- Host: 10.1.5.22\n- Acceso como invitado habilitado.\n\n### Mitigación\n\nDeshabilitar el acceso anónimo y aplicar autenticación en el recurso compartido SMB.`,
    createdAt: '2023-09-10',
    updatedAt: '2023-09-11',
  }
];

export const vulnerabilities: Vulnerability[] = [
  {
    id: 'vuln-001',
    title_es: 'Inyección SQL (SQLi)',
    title_en: 'SQL Injection (SQLi)',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Una vulnerabilidad de inyección SQL permite a un atacante malicioso interferir con las consultas que una aplicación realiza a su base de datos. Esto puede resultar en la extracción no autorizada de datos, la modificación o eliminación de datos, y en algunos casos, la toma de control completa del servidor de base de datos.',
    description_en: 'A SQL injection vulnerability allows a malicious attacker to interfere with the queries that an application makes to its database. This can result in unauthorized data extraction, data modification or deletion, and in some cases, complete takeover of the database server.',
    mitigation_es: 'La mitigación principal es el uso de consultas parametrizadas (prepared statements). Como defensa secundaria, se debe validar y sanear toda la entrada del usuario para filtrar caracteres maliciosos y aplicar el principio de mínimo privilegio en los permisos del usuario de la base de datos.',
    mitigation_en: 'The primary mitigation is the use of parameterized queries (prepared statements). As a secondary defense, all user input should be validated and sanitized to filter out malicious characters, and the principle of least privilege should be applied to database user permissions.',
    tags: ['OWASP Top 10', 'A03:2021-Injection'],
    reference: 'CWE-89'
  },
  {
    id: 'vuln-002',
    title_es: 'Cross-Site Scripting (XSS) Reflejado',
    title_en: 'Reflected Cross-Site Scripting (XSS)',
    cvss: 6.1,
    severity: 'Medium',
    description_es: 'El XSS reflejado ocurre cuando una aplicación web recibe datos en una solicitud HTTP y los incluye en la respuesta inmediata de manera insegura. Un atacante puede engañar a un usuario para que haga clic en un enlace malicioso que inyecta un script en la página, el cual se ejecuta en el navegador de la víctima, permitiendo el robo de sesiones, la desfiguración de sitios o la redirección a sitios maliciosos.',
    description_en: 'Reflected XSS occurs when a web application receives data in an HTTP request and includes it in the immediate response in an unsafe way. An attacker can trick a user into clicking a malicious link that injects a script into the page, which then executes in the victim\'s browser, allowing session theft, site defacement, or redirection to malicious sites.',
    mitigation_es: 'La mitigación principal es la codificación de salida (Output Encoding) de todos los datos no confiables antes de ser mostrados en el navegador. Implementar una Política de Seguridad de Contenido (CSP) robusta también es una medida de defensa en profundidad eficaz.',
    mitigation_en: 'The primary mitigation is Output Encoding of all untrusted data before it is displayed in the browser. Implementing a robust Content Security Policy (CSP) is also an effective defense-in-depth measure.',
    tags: ['OWASP Top 10', 'A03:2021-Injection'],
    reference: 'CWE-79'
  },
  {
    id: 'vuln-003',
    title_es: 'Componentes con Vulnerabilidades Conocidas',
    title_en: 'Vulnerable and Outdated Components',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Las aplicaciones y APIs que utilizan componentes (librerías, frameworks) con vulnerabilidades conocidas pueden ser explotadas por atacantes. Si una versión vulnerable de un componente es explotada, puede resultar en pérdida de datos, interrupción del servicio o la toma de control del servidor.',
    description_en: 'Applications and APIs using components (libraries, frameworks) with known vulnerabilities can be exploited by attackers. If a vulnerable version of a component is exploited, it can lead to data loss, service disruption, or server takeover.',
    mitigation_es: 'Mantener un inventario de todos los componentes de software de terceros y sus versiones. Monitorear fuentes de vulnerabilidades (como CVEs) y aplicar parches o actualizaciones de seguridad de manera oportuna. Utilizar herramientas de análisis de composición de software (SCA).',
    mitigation_en: 'Maintain an inventory of all third-party software components and their versions. Monitor vulnerability sources (like CVEs) and apply security patches or updates in a timely manner. Use Software Composition Analysis (SCA) tools.',
    tags: ['OWASP Top 10', 'A06:2021-Vulnerable and Outdated Components'],
    reference: 'CWE-1104'
  },
  {
    id: 'vuln-004',
    title_es: 'Pérdida de Control de Acceso',
    title_en: 'Broken Access Control',
    cvss: 8.8,
    severity: 'High',
    description_es: 'Esta vulnerabilidad ocurre cuando las restricciones sobre lo que los usuarios autenticados pueden hacer no se aplican correctamente. Un atacante puede explotar estos fallos para acceder a funcionalidades o datos no autorizados, como acceder a cuentas de otros usuarios, ver archivos sensibles o modificar datos y permisos de otros.',
    description_en: 'This vulnerability occurs when restrictions on what authenticated users are allowed to do are not properly enforced. An attacker can exploit these flaws to access unauthorized functionality or data, such as accessing other users\' accounts, viewing sensitive files, or modifying other users\' data and permissions.',
    mitigation_es: 'Implementar un modelo de control de acceso robusto basado en el principio de mínimo privilegio y denegación por defecto. Forzar las verificaciones de control de acceso en cada solicitud del lado del servidor. Invalidar sesiones después del cierre de sesión y en periodos de inactividad.',
    mitigation_en: 'Implement a robust access control model based on the principle of least privilege and deny-by-default. Enforce access control checks on every server-side request. Invalidate sessions after logout and on inactivity periods.',
    tags: ['OWASP Top 10', 'A01:2021-Broken Access Control'],
    reference: 'CWE-284'
  },
  {
    id: 'vuln-005',
    title_es: 'Fallo de Configuración de Seguridad',
    title_en: 'Security Misconfiguration',
    cvss: 7.5,
    severity: 'High',
    description_es: 'Las configuraciones de seguridad incorrectas son una de las vulnerabilidades más comunes. Esto puede incluir configuraciones por defecto inseguras, cabeceras HTTP mal configuradas, mensajes de error demasiado detallados o no deshabilitar funcionalidades innecesarias (p. ej., puertos, servicios, páginas, cuentas).',
    description_en: 'Incorrect security configurations are one of the most common vulnerabilities. This can include insecure default settings, misconfigured HTTP headers, overly detailed error messages, or not disabling unnecessary features (e.g., ports, services, pages, accounts).',
    mitigation_es: 'Implementar un proceso de "hardening" para el servidor de aplicaciones, framework, y base de datos. Automatizar el proceso de configuración para minimizar errores manuales. Revisar y actualizar las configuraciones de seguridad periódicamente. Configurar los mensajes de error para que no revelen información sensible.',
    mitigation_en: 'Implement a hardening process for the application server, framework, and database. Automate the configuration process to minimize manual errors. Review and update security configurations periodically. Configure error messages so they do not reveal sensitive information.',
    tags: ['OWASP Top 10', 'A05:2021-Security Misconfiguration'],
    reference: 'CWE-16'
  },
  {
    id: 'vuln-006',
    title_es: 'Fallo Criptográfico',
    title_en: 'Cryptographic Failures',
    cvss: 7.5,
    severity: 'High',
    description_es: 'Esta vulnerabilidad, anteriormente conocida como "Exposición de Datos Sensibles", se enfoca en fallos relacionados con la criptografía (o la falta de ella). El uso de algoritmos débiles o anticuados, la mala gestión de claves, o no cifrar datos sensibles en tránsito y en reposo puede exponer información crítica.',
    description_en: 'This vulnerability, formerly known as "Sensitive Data Exposure," focuses on failures related to cryptography (or lack thereof). Using weak or outdated algorithms, poor key management, or not encrypting sensitive data in transit and at rest can expose critical information.',
    mitigation_es: 'Clasificar los datos y aplicar controles criptográficos según su sensibilidad. Cifrar todos los datos sensibles en tránsito (TLS) y en reposo. Utilizar algoritmos criptográficos fuertes y actualizados con una gestión de claves segura. Deshabilitar el almacenamiento en caché de respuestas que contienen datos sensibles.',
    mitigation_en: 'Classify data and apply cryptographic controls based on sensitivity. Encrypt all sensitive data in transit (TLS) and at rest. Use strong, up-to-date cryptographic algorithms with secure key management. Disable caching for responses that contain sensitive data.',
    tags: ['OWASP Top 10', 'A02:2021-Cryptographic Failures'],
    reference: 'CWE-310'
  },
  {
    id: 'vuln-007',
    title_es: 'Cross-Site Scripting (XSS) Almacenado',
    title_en: 'Stored Cross-Site Scripting (XSS)',
    cvss: 8.8,
    severity: 'High',
    description_es: 'En el XSS Almacenado, el script malicioso se almacena permanentemente en el servidor de destino (p. ej., en una base de datos, en un foro, en un campo de comentario). La víctima recupera el script malicioso de la aplicación cuando solicita la información almacenada, lo que lleva a su ejecución en el navegador.',
    description_en: 'In Stored XSS, the malicious script is permanently stored on the target server (e.g., in a database, a forum, a comment field). The victim retrieves the malicious script from the application when requesting the stored information, leading to its execution in the browser.',
    mitigation_es: 'La principal mitigación es una rigurosa validación de entrada y codificación de salida. Cada dato que provenga del usuario y vaya a ser almacenado debe ser validado y, al mostrarse, debe ser codificado según el contexto (HTML, JS, CSS).',
    mitigation_en: 'The primary mitigation is rigorous input validation and output encoding. Every piece of user-provided data that will be stored must be validated, and upon display, it must be encoded according to the context (HTML, JS, CSS).',
    tags: ['OWASP Top 10', 'A03:2021-Injection'],
    reference: 'CWE-79'
  },
  {
    id: 'vuln-008',
    title_es: 'Cross-Site Request Forgery (CSRF)',
    title_en: 'Cross-Site Request Forgery (CSRF)',
    cvss: 8.8,
    severity: 'High',
    description_es: 'CSRF es un ataque que obliga a un usuario final a ejecutar acciones no deseadas en una aplicación web en la que está autenticado. Con un poco de ayuda de ingeniería social (como enviar un enlace por correo electrónico), un atacante puede hacer que las víctimas realicen acciones que el atacante elige.',
    description_en: 'CSRF is an attack that forces an end user to execute unwanted actions on a web application in which they are currently authenticated. With a little help from social engineering (such as sending a link via email), an attacker may trick the victims into performing actions of the attacker\'s choosing.',
    mitigation_es: 'La mitigación más robusta es el uso de un token anti-CSRF. Este token es un valor único y secreto que se añade a cada solicitud de cambio de estado y es verificado por el servidor. Otras medidas incluyen el uso de la bandera SameSite en las cookies.',
    mitigation_en: 'The most robust mitigation is the use of an anti-CSRF token. This token is a unique, secret value that is added to each state-changing request and verified by the server. Other measures include using the SameSite flag on cookies.',
    tags: ['CSRF'],
    reference: 'CWE-352'
  },
  {
    id: 'vuln-009',
    title_es: 'Inyección de Comandos del Sistema Operativo',
    title_en: 'OS Command Injection',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Esta vulnerabilidad permite a un atacante ejecutar comandos arbitrarios en el sistema operativo del servidor. Ocurre cuando la aplicación incorpora datos no saneados proporcionados por el usuario en un comando del sistema operativo.',
    description_en: 'This vulnerability allows an attacker to execute arbitrary commands on the server\'s operating system. It occurs when the application incorporates unsanitized user-provided data into an OS command.',
    mitigation_es: 'Evitar por completo el uso de llamadas al sistema operativo con entrada del usuario. Si es absolutamente necesario, utilizar APIs seguras que no pasen por el shell del sistema. Validar estrictamente la entrada del usuario contra una lista blanca de valores permitidos.',
    mitigation_en: 'Completely avoid using OS calls with user input. If absolutely necessary, use secure APIs that do not go through the system shell. Strictly validate user input against a whitelist of allowed values.',
    tags: ['OWASP Top 10', 'A03:2021-Injection'],
    reference: 'CWE-78'
  },
  {
    id: 'vuln-010',
    title_es: 'XML External Entity (XXE) Injection',
    title_en: 'XML External Entity (XXE) Injection',
    cvss: 9.1,
    severity: 'Critical',
    description_es: 'Un ataque de Entidades Externas XML (XXE) es un tipo de ataque contra una aplicación que procesa entradas XML. Este ataque ocurre cuando una entrada XML que contiene una referencia a una entidad externa es procesada por un procesador XML débilmente configurado.',
    description_en: 'An XML External Entities (XXE) attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser.',
    mitigation_es: 'Deshabilitar el procesamiento de entidades externas (DOCTYPE) en todos los procesadores XML de la aplicación. Configurar los procesadores para que no resuelvan entidades externas.',
    mitigation_en: 'Disable the processing of external entities (DOCTYPE) in all XML parsers in the application. Configure parsers to not resolve external entities.',
    tags: ['OWASP Top 10', 'A05:2021-Security Misconfiguration'],
    reference: 'CWE-611'
  },
  {
    id: 'vuln-011',
    title_es: 'Server-Side Request Forgery (SSRF)',
    title_en: 'Server-Side Request Forgery (SSRF)',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'SSRF es una vulnerabilidad que permite a un atacante inducir a la aplicación del lado del servidor a realizar peticiones a un dominio elegido por el atacante. Esto puede permitir al atacante interactuar con servicios internos de la red que de otro modo serían inaccesibles.',
    description_en: 'SSRF is a vulnerability that allows an attacker to induce the server-side application to make requests to an attacker-chosen domain. This can allow the attacker to interact with internal network services that would otherwise be inaccessible.',
    mitigation_es: 'Implementar una lista blanca (whitelist) de dominios, IPs y puertos a los que la aplicación puede realizar peticiones. Validar que la URL recibida coincida con los destinos permitidos. No enviar respuestas "crudas" del servidor solicitado de vuelta al cliente.',
    mitigation_en: 'Implement a whitelist of domains, IPs, and ports to which the application can make requests. Validate that the received URL matches the allowed destinations. Do not send raw responses from the requested server back to the client.',
    tags: ['OWASP Top 10', 'A10:2021-Server-Side Request Forgery'],
    reference: 'CWE-918'
  },
  {
    id: 'vuln-012',
    title_es: 'Fallo en la Monitorización y Registro de Seguridad',
    title_en: 'Security Logging and Monitoring Failures',
    cvss: 7.2,
    severity: 'High',
    description_es: 'La falta de un registro y monitoreo adecuados de los eventos de seguridad dificulta la detección de brechas de seguridad, la respuesta a incidentes y la investigación forense. Sin registros, los ataques pueden pasar desapercibidos durante largos períodos.',
    description_en: 'Lack of adequate logging and monitoring of security events makes it difficult to detect security breaches, respond to incidents, and conduct forensic investigations. Without logs, attacks can go unnoticed for long periods.',
    mitigation_es: 'Registrar eventos de seguridad clave como inicios de sesión (exitosos y fallidos), fallos de control de acceso y cambios de configuración. Asegurar que los registros contengan suficiente contexto. Implementar alertas en tiempo real para actividades sospechosas y proteger los registros contra la manipulación.',
    mitigation_en: 'Log key security events such as logins (successful and failed), access control failures, and configuration changes. Ensure logs contain sufficient context. Implement real-time alerts for suspicious activities and protect logs against tampering.',
    tags: ['OWASP Top 10', 'A09:2021-Security Logging and Monitoring Failures'],
    reference: 'CWE-778'
  },
  {
    id: 'vuln-013',
    title_es: 'Directory Traversal / Path Traversal',
    title_en: 'Directory Traversal / Path Traversal',
    cvss: 7.5,
    severity: 'High',
    description_es: 'Path Traversal es una vulnerabilidad que permite a un atacante leer archivos arbitrarios en el servidor. Ocurre cuando la aplicación utiliza la entrada del usuario para construir una ruta de archivo sin sanearla adecuadamente, permitiendo el uso de secuencias como "../".',
    description_en: 'Path Traversal is a vulnerability that allows an attacker to read arbitrary files on the server. It occurs when the application uses user input to construct a file path without proper sanitization, allowing the use of sequences like "../".',
    mitigation_es: 'La forma más efectiva de mitigar esta vulnerabilidad es evitar pasar entradas del usuario a las APIs del sistema de archivos. Si es inevitable, la aplicación debe validar la entrada del usuario y asegurarse de que la ruta canónica del archivo esté dentro del directorio esperado.',
    mitigation_en: 'The most effective way to mitigate this vulnerability is to avoid passing user input to file system APIs. If unavoidable, the application should validate user input and ensure that the canonical path of the file is within the expected directory.',
    tags: ['Path Traversal'],
    reference: 'CWE-22'
  },
  {
    id: 'vuln-014',
    title_es: 'Deserialización Insegura',
    title_en: 'Insecure Deserialization',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'La deserialización insegura a menudo conduce a la ejecución remota de código. Incluso si los fallos de deserialización no resultan en la ejecución remota de código, pueden ser utilizados para realizar ataques, incluyendo ataques de repetición, ataques de inyección y ataques de elevación de privilegios.',
    description_en: 'Insecure deserialization often leads to remote code execution. Even if deserialization flaws do not result in remote code execution, they can be used to perform attacks, including replay attacks, injection attacks, and privilege escalation attacks.',
    mitigation_es: 'La única forma segura de protegerse contra los ataques de deserialización es no aceptar objetos serializados de fuentes no confiables o usar formatos de serialización que solo permitan tipos de datos primitivos. Si se aceptan, implementar verificaciones de integridad criptográfica.',
    mitigation_en: 'The only safe way to protect against deserialization attacks is to not accept serialized objects from untrusted sources or to use serialization formats that only allow primitive data types. If accepted, implement cryptographic integrity checks.',
    tags: ['OWASP Top 10', 'A08:2021-Software and Data Integrity Failures'],
    reference: 'CWE-502'
  },
  {
    id: 'vuln-015',
    title_es: 'Redirección y Reenvío no Validados',
    title_en: 'Unvalidated Redirects and Forwards',
    cvss: 6.1,
    severity: 'Medium',
    description_es: 'Las aplicaciones web que redirigen a los usuarios a otras páginas y sitios web, y utilizan datos no confiables para determinar la página de destino, son susceptibles a esta vulnerabilidad. Un atacante puede construir una URL que redirija a la víctima a un sitio de phishing o malware.',
    description_en: 'Web applications that redirect users to other pages and websites, and use untrusted data to determine the destination page, are susceptible to this vulnerability. An attacker can construct a URL that redirects the victim to a phishing or malware site.',
    mitigation_es: 'Evitar el uso de redirecciones y reenvíos. Si se utilizan, no incluir parámetros de usuario en el destino. Si se requiere, validar que la URL de destino sea segura, esté dentro de la aplicación o en una lista blanca de dominios permitidos.',
    mitigation_en: 'Avoid using redirects and forwards. If used, do not include user parameters in the destination. If required, validate that the destination URL is safe, within the application, or on a whitelist of allowed domains.',
    tags: ['Open Redirect'],
    reference: 'CWE-601'
  },
  {
    id: 'vuln-016',
    title_es: 'Inclusión de Archivos Locales (LFI)',
    title_en: 'Local File Inclusion (LFI)',
    cvss: 7.5,
    severity: 'High',
    description_es: 'La Inclusión de Archivos Locales (LFI) es una vulnerabilidad que permite a un atacante incluir un archivo, generalmente a través de un script en el servidor web. La vulnerabilidad ocurre debido al uso de la entrada del usuario sin una validación adecuada, lo que permite la manipulación de la ruta del archivo.',
    description_en: 'Local File Inclusion (LFI) is a vulnerability that allows an attacker to include a file, usually through a script on the web server. The vulnerability occurs due to the use of user input without proper validation, allowing file path manipulation.',
    mitigation_es: 'La mitigación más efectiva es evitar pasar entradas proporcionadas por el usuario a funciones de inclusión de archivos. Si es necesario, se debe sanear rigurosamente la entrada o utilizar una lista blanca de archivos que pueden ser incluidos.',
    mitigation_en: 'The most effective mitigation is to avoid passing user-provided input to file inclusion functions. If necessary, the input should be rigorously sanitized or a whitelist of files that can be included should be used.',
    tags: ['LFI'],
    reference: 'CWE-98'
  },
  {
    id: 'vuln-017',
    title_es: 'Inclusión de Archivos Remotos (RFI)',
    title_en: 'Remote File Inclusion (RFI)',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'La Inclusión de Archivos Remotos (RFI) es una vulnerabilidad en la que un atacante puede hacer que la aplicación web en el servidor incluya un archivo alojado en un servidor remoto. Esto puede llevar a la ejecución de código arbitrario en el servidor.',
    description_en: 'Remote File Inclusion (RFI) is a vulnerability where an attacker can cause the web application on the server to include a file hosted on a remote server. This can lead to arbitrary code execution on the server.',
    mitigation_es: 'Deshabilitar `allow_url_include` y `allow_url_fopen` en la configuración de PHP. No confiar en la entrada del usuario al construir rutas de archivos para su inclusión. Usar una lista blanca de archivos permitidos.',
    mitigation_en: 'Disable `allow_url_include` and `allow_url_fopen` in the PHP configuration. Do not trust user input when constructing file paths for inclusion. Use a whitelist of allowed files.',
    tags: ['RFI'],
    reference: 'CWE-98'
  },
  {
    id: 'vuln-018',
    title_es: 'Carga de Archivos sin Restricciones',
    title_en: 'Unrestricted File Upload',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Si una aplicación permite a los usuarios subir archivos sin las restricciones adecuadas sobre el tipo de archivo, el tamaño o el contenido, un atacante podría subir un archivo malicioso (como un shell web) y ejecutar código arbitrario en el servidor.',
    description_en: 'If an application allows users to upload files without proper restrictions on file type, size, or content, an attacker could upload a malicious file (such as a web shell) and execute arbitrary code on the server.',
    mitigation_es: 'Validar el tipo de archivo utilizando una lista blanca de extensiones y tipos MIME permitidos. Renombrar los archivos subidos para evitar la ejecución directa. Almacenar los archivos subidos fuera del directorio raíz de la web. Limitar el tamaño del archivo.',
    mitigation_en: 'Validate the file type using a whitelist of allowed extensions and MIME types. Rename uploaded files to prevent direct execution. Store uploaded files outside the web root directory. Limit the file size.',
    tags: ['File Upload'],
    reference: 'CWE-434'
  },
  {
    id: 'vuln-019',
    title_es: 'Falta de Cabeceras de Seguridad',
    title_en: 'Missing Security Headers',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La ausencia de cabeceras de seguridad HTTP como Content-Security-Policy (CSP), Strict-Transport-Security (HSTS), o X-Content-Type-Options puede dejar a la aplicación vulnerable a varios tipos de ataques, incluyendo XSS, clickjacking y sniffing de MIME.',
    description_en: 'The absence of HTTP security headers like Content-Security-Policy (CSP), Strict-Transport-Security (HSTS), or X-Content-Type-Options can leave the application vulnerable to various types of attacks, including XSS, clickjacking, and MIME sniffing.',
    mitigation_es: 'Configurar el servidor web para que envíe las cabeceras de seguridad HTTP apropiadas en todas las respuestas. Las cabeceras deben ser configuradas con directivas seguras y restrictivas.',
    mitigation_en: 'Configure the web server to send appropriate HTTP security headers in all responses. The headers should be configured with secure and restrictive directives.',
    tags: ['Security Misconfiguration'],
    reference: 'CWE-693'
  },
  {
    id: 'vuln-020',
    title_es: 'Clickjacking',
    title_en: 'Clickjacking',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'El Clickjacking es una técnica maliciosa para engañar a un usuario para que haga clic en algo diferente de lo que el usuario percibe, lo que podría revelar información confidencial o tomar el control de su computadora mientras hace clic en objetos aparentemente inofensivos.',
    description_en: 'Clickjacking is a malicious technique of tricking a user into clicking on something different from what the user perceives, thus potentially revealing confidential information or taking control of their computer while clicking on seemingly innocuous objects.',
    mitigation_es: 'La principal defensa contra el clickjacking es el uso de la cabecera HTTP X-Frame-Options con el valor "DENY" o "SAMEORIGIN", o utilizar la directiva "frame-ancestors" en una Content-Security-Policy (CSP).',
    mitigation_en: 'The primary defense against clickjacking is using the X-Frame-Options HTTP header with the value "DENY" or "SAMEORIGIN", or using the "frame-ancestors" directive in a Content-Security-Policy (CSP).',
    tags: ['UI Redressing'],
    reference: 'CWE-1021'
  },
  {
    id: 'vuln-021',
    title_es: 'Inyección de Plantillas del Lado del Servidor (SSTI)',
    title_en: 'Server-Side Template Injection (SSTI)',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'SSTI ocurre cuando la entrada del usuario se concatena o se incrusta de forma insegura en una plantilla. Un atacante puede inyectar código de plantilla malicioso para ejecutar comandos arbitrarios en el servidor.',
    description_en: 'SSTI occurs when user input is insecurely concatenated or embedded into a template. An attacker can inject malicious template code to execute arbitrary commands on the server.',
    mitigation_es: 'Evitar la modificación de plantillas con entrada del usuario. Utilizar entornos "sandbox" para el renderizado de plantillas si la entrada del usuario es necesaria. Sanear la entrada antes de pasarla al motor de plantillas.',
    mitigation_en: 'Avoid modifying templates with user input. Use "sandboxed" environments for template rendering if user input is necessary. Sanitize input before passing it to the template engine.',
    tags: ['SSTI'],
    reference: 'CWE-94'
  },
  {
    id: 'vuln-101',
    title_es: 'Fuga de Información a través de Comentarios en el Código Fuente',
    title_en: 'Information Disclosure through Source Code Comments',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'Los comentarios en el código fuente (HTML, CSS, JavaScript) a veces contienen información sensible como credenciales, nombres de archivos ocultos, rutas de directorios, o lógica de negocio que no debería ser pública. Esta información puede ser aprovechada por un atacante para planificar ataques más complejos.',
    description_en: 'Comments in the source code (HTML, CSS, JavaScript) sometimes contain sensitive information such as credentials, hidden filenames, directory paths, or business logic that should not be public. This information can be leveraged by an attacker to plan more complex attacks.',
    mitigation_es: 'Implementar un proceso de revisión de código para eliminar toda la información sensible de los comentarios antes de desplegar en producción. Utilizar herramientas de minificación y ofuscación que eliminen los comentarios automáticamente.',
    mitigation_en: 'Implement a code review process to remove all sensitive information from comments before deploying to production. Use minification and obfuscation tools that automatically remove comments.',
    tags: ['Information Disclosure'],
    reference: 'CWE-200'
  },
  {
    id: 'vuln-102',
    title_es: 'Gestión de Sesión Rota',
    title_en: 'Broken Session Management',
    cvss: 7.5,
    severity: 'High',
    description_es: 'Una gestión de sesión insegura puede permitir a los atacantes secuestrar sesiones de usuarios legítimos. Esto incluye IDs de sesión predecibles, no invalidar sesiones después de cerrar sesión, o transmitir IDs de sesión en texto plano (en URLs).',
    description_en: 'Insecure session management can allow attackers to hijack legitimate user sessions. This includes predictable session IDs, not invalidating sessions after logout, or transmitting session IDs in plaintext (in URLs).',
    mitigation_es: 'Generar IDs de sesión largos, aleatorios e impredecibles. Invalidar la sesión en el servidor después del cierre de sesión. Regenerar el ID de sesión después de un inicio de sesión exitoso. Configurar la bandera `Secure` y `HttpOnly` en las cookies de sesión.',
    mitigation_en: 'Generate long, random, and unpredictable session IDs. Invalidate the session on the server after logout. Regenerate the session ID after a successful login. Set the `Secure` and `HttpOnly` flags on session cookies.',
    tags: ['OWASP Top 10', 'A07:2021-Identification and Authentication Failures'],
    reference: 'CWE-613'
  },
  {
    id: 'vuln-103',
    title_es: 'Uso de Componentes Criptográficos Débiles o Anticuados',
    title_en: 'Use of Weak or Outdated Cryptographic Components',
    cvss: 7.5,
    severity: 'High',
    description_es: 'El uso de algoritmos de cifrado, hashing o firmas digitales que se sabe que son débiles (como MD5, SHA1, DES) expone a la aplicación a ataques criptoanalíticos. Un atacante podría ser capaz de descifrar datos, falsificar firmas o adivinar hashes.',
    description_en: 'Using encryption, hashing, or digital signature algorithms that are known to be weak (such as MD5, SHA1, DES) exposes the application to cryptanalytic attacks. An attacker might be able to decrypt data, forge signatures, or guess hashes.',
    mitigation_es: 'Utilizar algoritmos criptográficos estándar de la industria y recomendados actualmente (p. ej., AES-256, SHA-256, RSA con claves de 2048 bits o más). Mantenerse actualizado sobre las mejores prácticas criptográficas y migrar de algoritmos débiles tan pronto como sea posible.',
    mitigation_en: 'Use industry-standard and currently recommended cryptographic algorithms (e.g., AES-256, SHA-256, RSA with 2048-bit keys or longer). Stay updated on cryptographic best practices and migrate from weak algorithms as soon as possible.',
    tags: ['OWASP Top 10', 'A02:2021-Cryptographic Failures'],
    reference: 'CWE-327'
  },
  {
    id: 'vuln-104',
    title_es: 'Enumeración de Usuarios',
    title_en: 'User Enumeration',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La aplicación proporciona diferentes respuestas para nombres de usuario válidos e inválidos en funciones como "recuperar contraseña" o en el inicio de sesión. Esto permite a un atacante construir una lista de usuarios válidos en el sistema.',
    description_en: 'The application provides different responses for valid and invalid usernames in functions like "password recovery" or login. This allows an attacker to build a list of valid users in the system.',
    mitigation_es: 'Implementar respuestas genéricas para los intentos de inicio de sesión y recuperación de contraseña, independientemente de si el nombre de usuario existe o no. Por ejemplo, "Si el usuario existe, se enviará un correo electrónico de recuperación".',
    mitigation_en: 'Implement generic responses for login and password recovery attempts, regardless of whether the username exists or not. For example, "If the user exists, a recovery email will be sent."',
    tags: ['Authentication'],
    reference: 'CWE-204'
  },
  {
    id: 'vuln-105',
    title_es: 'Políticas de Contraseña Débiles',
    title_en: 'Weak Password Policy',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La aplicación no exige políticas de contraseñas suficientemente robustas, permitiendo contraseñas cortas, simples o fáciles de adivinar. Esto aumenta el riesgo de ataques de fuerza bruta o de diccionario.',
    description_en: 'The application does not enforce sufficiently strong password policies, allowing short, simple, or easily guessable passwords. This increases the risk of brute-force or dictionary attacks.',
    mitigation_es: 'Implementar una política de contraseñas que requiera una longitud mínima (p. ej., 12 caracteres), complejidad (mezcla de mayúsculas, minúsculas, números y símbolos) y comparar las contraseñas nuevas con una lista de contraseñas comunes o comprometidas. Implementar bloqueo de cuentas después de múltiples intentos fallidos.',
    mitigation_en: 'Implement a password policy that requires a minimum length (e.g., 12 characters), complexity (mix of uppercase, lowercase, numbers, and symbols), and check new passwords against a list of common or compromised passwords. Implement account lockout after multiple failed attempts.',
    tags: ['Authentication'],
    reference: 'CWE-521'
  },
  {
    id: 'vuln-106',
    title_es: 'Falta del Atributo "HttpOnly" en Cookies de Sesión',
    title_en: 'Missing "HttpOnly" Attribute on Session Cookies',
    cvss: 6.1,
    severity: 'Medium',
    description_es: 'Si la cookie de sesión no tiene el atributo `HttpOnly`, puede ser accedida por scripts del lado del cliente (JavaScript). En caso de una vulnerabilidad de XSS, un atacante podría robar la cookie de sesión y secuestrar la sesión del usuario.',
    description_en: 'If the session cookie does not have the `HttpOnly` attribute, it can be accessed by client-side scripts (JavaScript). In the event of an XSS vulnerability, an attacker could steal the session cookie and hijack the user\'s session.',
    mitigation_es: 'Configurar el atributo `HttpOnly` en todas las cookies que no necesiten ser accedidas por JavaScript, especialmente las cookies de sesión.',
    mitigation_en: 'Set the `HttpOnly` attribute on all cookies that do not need to be accessed by JavaScript, especially session cookies.',
    tags: ['Session Management'],
    reference: 'CWE-1004'
  },
  {
    id: 'vuln-107',
    title_es: 'Falta del Atributo "Secure" en Cookies Sensibles',
    title_en: 'Missing "Secure" Attribute on Sensitive Cookies',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'Si una cookie sensible (como una cookie de sesión) no tiene el atributo `Secure`, el navegador podría transmitirla a través de una conexión HTTP no cifrada. Un atacante en la red podría interceptar la cookie y comprometer la sesión.',
    description_en: 'If a sensitive cookie (like a session cookie) does not have the `Secure` attribute, the browser might transmit it over an unencrypted HTTP connection. An attacker on the network could intercept the cookie and compromise the session.',
    mitigation_es: 'Configurar el atributo `Secure` en todas las cookies que contengan información sensible. Esto asegura que solo se envíen a través de conexiones HTTPS.',
    mitigation_en: 'Set the `Secure` attribute on all cookies containing sensitive information. This ensures they are only sent over HTTPS connections.',
    tags: ['Session Management'],
    reference: 'CWE-614'
  },
  {
    id: 'vuln-108',
    title_es: 'Exposición de Versión de Software',
    title_en: 'Software Version Exposure',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La aplicación revela las versiones específicas del software del servidor web, framework, o componentes de terceros en las cabeceras HTTP o páginas de error. Un atacante puede usar esta información para buscar vulnerabilidades conocidas para esa versión específica.',
    description_en: 'The application reveals specific versions of the web server software, framework, or third-party components in HTTP headers or error pages. An attacker can use this information to look for known vulnerabilities for that specific version.',
    mitigation_es: 'Configurar el servidor web y la aplicación para no revelar información de versión en las cabeceras de respuesta (p. ej., `Server`, `X-Powered-By`) y en las páginas de error.',
    mitigation_en: 'Configure the web server and application not to reveal version information in response headers (e.g., `Server`, `X-Powered-By`) and error pages.',
    tags: ['Information Disclosure'],
    reference: 'CWE-200'
  },
  {
    id: 'vuln-109',
    title_es: 'Business Logic Flaw',
    title_en: 'Business Logic Flaw',
    cvss: 6.5,
    severity: 'Medium',
    description_es: 'Una falla en la lógica de negocio permite a un atacante eludir reglas de negocio o realizar acciones no previstas por la aplicación. Por ejemplo, manipular precios en un carrito de compras o votar varias veces en una encuesta.',
    description_en: 'A business logic flaw allows an attacker to bypass business rules or perform actions not intended by the application. For example, manipulating prices in a shopping cart or voting multiple times in a poll.',
    mitigation_es: 'Requiere una comprensión profunda del flujo de negocio de la aplicación. Las mitigaciones son específicas para cada caso, pero generalmente implican validaciones del lado del servidor más estrictas en cada paso del proceso de negocio.',
    mitigation_en: 'Requires a deep understanding of the application\'s business flow. Mitigations are case-specific but generally involve stricter server-side validations at each step of the business process.',
    tags: ['Business Logic'],
    reference: 'CWE-840'
  },
  {
    id: 'vuln-110',
    title_es: 'Falta de Rate Limiting en Funciones Críticas',
    title_en: 'Missing Rate Limiting on Critical Functions',
    cvss: 7.5,
    severity: 'High',
    description_es: 'La ausencia de limitación de tasa (rate limiting) en funciones críticas como el inicio de sesión, recuperación de contraseña o APIs permite ataques de fuerza bruta automatizados. Un atacante podría intentar adivinar contraseñas o enviar spam masivo.',
    description_en: 'The absence of rate limiting on critical functions like login, password recovery, or APIs allows for automated brute-force attacks. An attacker could attempt to guess passwords or send massive amounts of spam.',
    mitigation_es: 'Implementar un mecanismo de limitación de tasa basado en IP, ID de usuario, o token de sesión para las funciones críticas. Después de un cierto número de intentos fallidos en un período de tiempo, bloquear temporalmente o requerir un CAPTCHA.',
    mitigation_en: 'Implement a rate-limiting mechanism based on IP, user ID, or session token for critical functions. After a certain number of failed attempts within a time period, temporarily block or require a CAPTCHA.',
    tags: ['Brute Force'],
    reference: 'CWE-307'
  },
  {
    id: 'vuln-111',
    title_es: 'Cross-Origin Resource Sharing (CORS) Mal Configurado',
    title_en: 'Misconfigured Cross-Origin Resource Sharing (CORS)',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'Una configuración de CORS demasiado permisiva, como reflejar el origen de la solicitud en la cabecera `Access-Control-Allow-Origin`, puede permitir que un sitio web malicioso realice solicitudes a la aplicación en nombre del usuario y lea la respuesta.',
    description_en: 'An overly permissive CORS configuration, such as reflecting the request\'s origin in the `Access-Control-Allow-Origin` header, can allow a malicious website to make requests to the application on behalf of the user and read the response.',
    mitigation_es: 'Configurar una lista blanca estricta de orígenes permitidos en la cabecera `Access-Control-Allow-Origin`. Evitar el uso de valores dinámicos o comodines como `*` a menos que el recurso sea verdaderamente público.',
    mitigation_en: 'Configure a strict whitelist of allowed origins in the `Access-Control-Allow-Origin` header. Avoid using dynamic values or wildcards like `*` unless the resource is truly public.',
    tags: ['CORS'],
    reference: 'CWE-942'
  },
  {
    id: 'vuln-112',
    title_es: 'Inyección de LDAP',
    title_en: 'LDAP Injection',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Similar a la inyección SQL, pero dirigida a servidores LDAP. Si la entrada del usuario no se sanea correctamente, un atacante puede construir sentencias LDAP maliciosas para bypassar la autenticación o modificar/extraer datos del directorio LDAP.',
    description_en: 'Similar to SQL injection, but targeted at LDAP servers. If user input is not properly sanitized, an attacker can construct malicious LDAP statements to bypass authentication or modify/extract data from the LDAP directory.',
    mitigation_es: 'Utilizar frameworks que proporcionen funciones para escapar automáticamente los caracteres especiales de LDAP. Evitar construir consultas LDAP mediante la concatenación de cadenas. Validar la entrada del usuario.',
    mitigation_en: 'Use frameworks that provide functions to automatically escape LDAP special characters. Avoid building LDAP queries by string concatenation. Validate user input.',
    tags: ['Injection'],
    reference: 'CWE-90'
  },
  {
    id: 'vuln-113',
    title_es: 'Inyección de XPath',
    title_en: 'XPath Injection',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Similar a la inyección SQL, pero el atacante inyecta datos en una aplicación para construir una consulta XPath maliciosa. Esto puede permitir al atacante bypassar la autenticación o extraer datos de documentos XML.',
    description_en: 'Similar to SQL injection, but the attacker injects data into an application to construct a malicious XPath query. This can allow the attacker to bypass authentication or extract data from XML documents.',
    mitigation_es: 'Evitar la construcción de consultas XPath con datos del usuario. Utilizar APIs parametrizadas si están disponibles. Sanear la entrada del usuario para filtrar caracteres que tienen un significado especial en XPath.',
    mitigation_en: 'Avoid constructing XPath queries with user data. Use parameterized APIs if available. Sanitize user input to filter characters that have special meaning in XPath.',
    tags: ['Injection'],
    reference: 'CWE-643'
  },
  {
    id: 'vuln-114',
    title_es: 'Inyección de NoSQL',
    title_en: 'NoSQL Injection',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'La inyección de NoSQL ocurre cuando la entrada del usuario se concatena de forma insegura en una consulta para una base de datos NoSQL (como MongoDB). Un atacante puede inyectar operadores de consulta para alterar la lógica y bypassar la autenticación o extraer datos.',
    description_en: 'NoSQL injection occurs when user input is insecurely concatenated into a query for a NoSQL database (like MongoDB). An attacker can inject query operators to alter the logic and bypass authentication or extract data.',
    mitigation_es: 'Evitar construir consultas mediante concatenación de cadenas. Utilizar las APIs de consulta seguras proporcionadas por el motor de base de datos NoSQL, que a menudo son análogas a las consultas parametrizadas. Validar y sanear la entrada del usuario.',
    mitigation_en: 'Avoid building queries through string concatenation. Use the secure query APIs provided by the NoSQL database engine, which are often analogous to parameterized queries. Validate and sanitize user input.',
    tags: ['Injection'],
    reference: 'CWE-943'
  },
  {
    id: 'vuln-115',
    title_es: 'Inyección de Cabecera de Host',
    title_en: 'Host Header Injection',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La aplicación utiliza la cabecera `Host` de la solicitud HTTP de forma insegura, por ejemplo, para generar URLs en enlaces de restablecimiento de contraseña. Un atacante puede manipular esta cabecera para que la aplicación genere un enlace que apunte a un dominio malicioso, facilitando ataques de phishing.',
    description_en: 'The application uses the `Host` header from the HTTP request insecurely, for example, to generate URLs in password reset links. An attacker can manipulate this header so that the application generates a link pointing to a malicious domain, facilitating phishing attacks.',
    mitigation_es: 'No confiar en la cabecera `Host`. Utilizar una variable de configuración del lado del servidor que contenga el nombre de host canónico de la aplicación para generar todas las URLs absolutas.',
    mitigation_en: 'Do not trust the `Host` header. Use a server-side configuration variable containing the canonical hostname of the application to generate all absolute URLs.',
    tags: ['Host Header'],
    reference: 'CWE-74'
  },
  {
    id: 'vuln-116',
    title_es: 'Comparación de Cadenas Insegura',
    title_en: 'Insecure String Comparison',
    cvss: 5.9,
    severity: 'Medium',
    description_es: 'El uso de funciones de comparación de cadenas que no son seguras en tiempo constante para comparar valores secretos (como tokens o firmas) puede ser vulnerable a ataques de temporización. Un atacante podría medir el tiempo de respuesta para adivinar el valor secreto carácter por carácter.',
    description_en: 'Using string comparison functions that are not constant-time safe to compare secret values (like tokens or signatures) can be vulnerable to timing attacks. An attacker could measure the response time to guess the secret value character by character.',
    mitigation_es: 'Utilizar funciones de comparación seguras en tiempo constante (constant-time comparison functions) proporcionadas por librerías criptográficas para comparar cualquier valor secreto.',
    mitigation_en: 'Use constant-time comparison functions provided by cryptographic libraries to compare any secret values.',
    tags: ['Timing Attack'],
    reference: 'CWE-208'
  },
  {
    id: 'vuln-117',
    title_es: 'Uso de Funciones de Hash Débiles para Contraseñas',
    title_en: 'Use of Weak Password Hashing Functions',
    cvss: 7.5,
    severity: 'High',
    description_es: 'El almacenamiento de contraseñas utilizando funciones de hash rápidas como MD5 o SHA-256 (sin sal) es inseguro. Estas funciones son susceptibles a ataques de diccionario y de tabla arcoíris, y pueden ser crackeadas rápidamente con hardware moderno.',
    description_en: 'Storing passwords using fast hash functions like MD5 or SHA-256 (without a salt) is insecure. These functions are susceptible to dictionary and rainbow table attacks and can be cracked quickly with modern hardware.',
    mitigation_es: 'Utilizar funciones de hashing de contraseñas adaptativas y lentas como Argon2, scrypt, o bcrypt. Estas funciones son computacionalmente intensivas y están diseñadas para resistir ataques de fuerza bruta. Siempre se debe usar una sal única por cada contraseña.',
    mitigation_en: 'Use slow, adaptive password hashing functions like Argon2, scrypt, or bcrypt. These functions are computationally intensive and designed to resist brute-force attacks. A unique salt should always be used for each password.',
    tags: ['Cryptographic Failures'],
    reference: 'CWE-916'
  },
  {
    id: 'vuln-118',
    title_es: 'Autocompletado Habilitado en Campos de Contraseña',
    title_en: 'Autocomplete Enabled on Password Fields',
    cvss: 3.1,
    severity: 'Low',
    description_es: 'El atributo `autocomplete` está habilitado en los campos de formulario para contraseñas. Esto puede hacer que el navegador del usuario almacene la contraseña, lo que podría ser un riesgo si la máquina del usuario es compartida o se ve comprometida.',
    description_en: 'The `autocomplete` attribute is enabled on password form fields. This can cause the user\'s browser to store the password, which could be a risk if the user\'s machine is shared or compromised.',
    mitigation_es: 'Añadir el atributo `autocomplete="new-password"` al campo de la contraseña para indicar a los navegadores que no deben almacenar el valor.',
    mitigation_en: 'Add the `autocomplete="new-password"` attribute to the password field to signal to browsers that they should not store the value.',
    tags: ['Security Misconfiguration'],
    reference: 'CWE-525'
  },
  {
    id: 'vuln-119',
    title_es: 'Falta de Protección contra la Fuerza Bruta en la Autenticación',
    title_en: 'Missing Brute Force Protection on Authentication',
    cvss: 7.5,
    severity: 'High',
    description_es: 'El formulario de inicio de sesión no implementa ningún mecanismo para prevenir o dificultar los ataques de fuerza bruta. Un atacante puede intentar un número ilimitado de combinaciones de usuario/contraseña para obtener acceso.',
    description_en: 'The login form does not implement any mechanism to prevent or hinder brute force attacks. An attacker can try an unlimited number of username/password combinations to gain access.',
    mitigation_es: 'Implementar un mecanismo de bloqueo de cuentas después de un número determinado de intentos fallidos. También se puede implementar un CAPTCHA después de unos pocos intentos fallidos o un retardo exponencial entre intentos.',
    mitigation_en: 'Implement an account lockout mechanism after a certain number of failed attempts. A CAPTCHA can also be implemented after a few failed attempts, or an exponential delay between attempts.',
    tags: ['Brute Force'],
    reference: 'CWE-307'
  },
  {
    id: 'vuln-120',
    title_es: 'HTTP Request Smuggling',
    title_en: 'HTTP Request Smuggling',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Esta técnica de ataque interfiere con la forma en que un sitio web procesa las secuencias de solicitudes HTTP que se reciben de uno o más usuarios. Permite a un atacante "contrabandear" una solicitud maliciosa al servidor, que puede ser procesada como si viniera de un usuario diferente. Esto puede resultar en el secuestro de sesión y el bypass de controles de seguridad.',
    description_en: 'This attack technique interferes with the way a website processes sequences of HTTP requests that are received from one or more users. It allows an attacker to "smuggle" a malicious request to the server, which can be processed as if it came from a different user. This can result in session hijacking and bypassing security controls.',
    mitigation_es: 'Deshabilitar la reutilización de la conexión de backend si es posible. Utilizar HTTP/2 para las conexiones de backend, ya que este protocolo previene la ambigüedad en las solicitudes. Asegurarse de que tanto el frontend como el backend normalicen las solicitudes ambiguas de la misma manera.',
    mitigation_en: 'Disable backend connection reuse if possible. Use HTTP/2 for backend connections, as this protocol prevents request ambiguity. Ensure that both the frontend and backend normalize ambiguous requests in the same way.',
    tags: ['HTTP'],
    reference: 'CWE-444'
  },
  {
    id: 'vuln-121',
    title_es: 'Exposición de Archivo .git',
    title_en: '.git Directory Exposure',
    cvss: 7.5,
    severity: 'High',
    description_es: 'El directorio `.git` se encuentra expuesto públicamente en el servidor web. Esto permite a un atacante descargar el repositorio completo, incluyendo el código fuente, el historial de cambios, y potencialmente información sensible como claves de API o contraseñas que se hayan commiteado accidentalmente.',
    description_en: 'The `.git` directory is publicly exposed on the web server. This allows an attacker to download the entire repository, including source code, change history, and potentially sensitive information such as API keys or passwords that have been accidentally committed.',
    mitigation_es: 'Configurar el servidor web para denegar el acceso al directorio `.git` y a su contenido. Asegurarse de que el proceso de despliegue no copie el directorio `.git` a los servidores de producción.',
    mitigation_en: 'Configure the web server to deny access to the `.git` directory and its contents. Ensure that the deployment process does not copy the `.git` directory to production servers.',
    tags: ['Information Disclosure'],
    reference: 'CWE-548'
  },
  {
    id: 'vuln-122',
    title_es: 'Subdomain Takeover',
    title_en: 'Subdomain Takeover',
    cvss: 7.2,
    severity: 'High',
    description_es: 'Un subdominio está apuntando a un servicio de terceros (p. ej., Heroku, S3) a través de un registro DNS (CNAME), pero el servicio ya no está en uso o ha sido eliminado. Un atacante puede registrar ese servicio y tomar control del subdominio para servir contenido malicioso.',
    description_en: 'A subdomain is pointing to a third-party service (e.g., Heroku, S3) via a DNS record (CNAME), but the service is no longer in use or has been deleted. An attacker can register that service and take control of the subdomain to serve malicious content.',
    mitigation_es: 'Realizar auditorías periódicas de los registros DNS para identificar y eliminar CNAMEs que apunten a recursos externos no utilizados. Eliminar el registro DNS antes de dar de baja el servicio externo correspondiente.',
    mitigation_en: 'Perform regular audits of DNS records to identify and remove CNAMEs pointing to unused external resources. Remove the DNS record before decommissioning the corresponding external service.',
    tags: ['DNS'],
    reference: 'CWE-350'
  },
  {
    id: 'vuln-123',
    title_es: 'Content Spoofing',
    title_en: 'Content Spoofing',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'La aplicación permite a un atacante inyectar texto o contenido arbitrario que es mostrado a otros usuarios. A diferencia de XSS, no implica la inyección de scripts, sino la manipulación del texto para engañar a los usuarios o dañar la reputación de la marca.',
    description_en: 'The application allows an attacker to inject arbitrary text or content that is displayed to other users. Unlike XSS, it does not involve script injection, but rather text manipulation to deceive users or damage brand reputation.',
    mitigation_es: 'Validar y sanear toda la entrada del usuario que vaya a ser mostrada. No permitir que la entrada del usuario controle directamente el contenido de la página. Codificar la salida si es posible.',
    mitigation_en: 'Validate and sanitize all user input that will be displayed. Do not allow user input to directly control page content. Encode output if possible.',
    tags: ['Content Spoofing'],
    reference: 'CWE-451'
  },
  {
    id: 'vuln-124',
    title_es: 'Divulgación de Pila de Errores (Stack Trace)',
    title_en: 'Stack Trace Disclosure',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'Cuando ocurre un error no controlado, la aplicación muestra una traza de pila (stack trace) completa al usuario. Esta información puede revelar detalles sobre el framework, las librerías utilizadas, rutas de archivos en el servidor y fragmentos de código, todo lo cual es útil para un atacante.',
    description_en: 'When an unhandled error occurs, the application displays a full stack trace to the user. This information can reveal details about the framework, libraries used, file paths on the server, and code snippets, all of which are useful to an attacker.',
    mitigation_es: 'Configurar la aplicación para que capture todos los errores y muestre una página de error genérica y amigable para el usuario. Los detalles completos del error y la traza de pila deben registrarse únicamente en el servidor para su posterior análisis por parte de los desarrolladores.',
    mitigation_en: 'Configure the application to catch all errors and display a generic, user-friendly error page. Full error details and the stack trace should only be logged on the server for later analysis by developers.',
    tags: ['Information Disclosure'],
    reference: 'CWE-209'
  },
  {
    id: 'vuln-125',
    title_es: 'API sin Autenticación para Recursos Sensibles',
    title_en: 'API without Authentication for Sensitive Resources',
    cvss: 8.8,
    severity: 'High',
    description_es: 'Un endpoint de la API que expone datos o funcionalidades sensibles no implementa ningún tipo de control de autenticación. Cualquier persona con conocimiento de la URL del endpoint puede acceder a él sin restricciones.',
    description_en: 'An API endpoint that exposes sensitive data or functionality does not implement any authentication controls. Anyone with knowledge of the endpoint URL can access it without restriction.',
    mitigation_es: 'Implementar un esquema de autenticación robusto para todos los endpoints de la API (p. ej., OAuth 2.0, JWT, claves de API). Asegurarse de que cada solicitud a un endpoint sensible sea debidamente autenticada y autorizada.',
    mitigation_en: 'Implement a robust authentication scheme for all API endpoints (e.g., OAuth 2.0, JWT, API keys). Ensure that every request to a sensitive endpoint is properly authenticated and authorized.',
    tags: ['API Security'],
    reference: 'CWE-306'
  },
  {
    id: 'vuln-126',
    title_es: 'Asignación Masiva Insegura (Mass Assignment)',
    title_en: 'Insecure Mass Assignment',
    cvss: 7.5,
    severity: 'High',
    description_es: 'La aplicación vincula directamente los datos de la solicitud del cliente a los objetos del modelo de datos sin una validación adecuada. Un atacante puede manipular la solicitud para establecer valores en propiedades que no deberían ser modificables, como el rol de un usuario (`isAdmin=true`).',
    description_en: 'The application directly binds client request data to data model objects without proper validation. An attacker can manipulate the request to set values on properties that should not be modifiable, such as a user\'s role (`isAdmin=true`).',
    mitigation_es: 'Evitar la vinculación automática de datos. En su lugar, utilizar DTOs (Data Transfer Objects) con una lista blanca de propiedades permitidas para cada operación. Mapear explícitamente los campos del DTO al modelo de datos del servidor.',
    mitigation_en: 'Avoid automatic data binding. Instead, use DTOs (Data Transfer Objects) with a whitelist of allowed properties for each operation. Explicitly map fields from the DTO to the server-side data model.',
    tags: ['API Security', 'OWASP API Top 10'],
    reference: 'CWE-915'
  },
  {
    id: 'vuln-127',
    title_es: 'Exposición Excesiva de Datos en API',
    title_en: 'Excessive Data Exposure in API',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'El endpoint de la API devuelve más datos de los que la interfaz de usuario necesita o muestra. Aunque el frontend filtre los datos sensibles, un atacante puede interceptar el tráfico de la API para obtener toda la información, incluyendo datos que no debería ver.',
    description_en: 'The API endpoint returns more data than the user interface needs or displays. Even if the frontend filters out sensitive data, an attacker can intercept the API traffic to obtain all the information, including data they should not see.',
    mitigation_es: 'Diseñar las respuestas de la API para que devuelvan solo los datos mínimos necesarios para cada caso de uso. Evitar la serialización genérica de objetos de la base de datos directamente en la respuesta. Utilizar DTOs específicos para cada respuesta.',
    mitigation_en: 'Design API responses to return only the minimum necessary data for each use case. Avoid generic serialization of database objects directly into the response. Use specific DTOs for each response.',
    tags: ['API Security', 'OWASP API Top 10'],
    reference: 'CWE-213'
  },
  {
    id: 'vuln-128',
    title_es: 'Ausencia de Recursos Límite en API',
    title_en: 'Lack of Resources & Rate Limiting in API',
    cvss: 7.5,
    severity: 'High',
    description_es: 'La API no restringe el número o la frecuencia de las solicitudes que un cliente puede realizar. Esto puede llevar a ataques de Denegación de Servicio (DoS), ya sea por agotamiento de recursos del servidor o por incurrir en altos costes en servicios cloud.',
    description_en: 'The API does not restrict the number or frequency of requests a client can make. This can lead to Denial of Service (DoS) attacks, either by exhausting server resources or by incurring high costs in cloud services.',
    mitigation_es: 'Implementar limitación de tasa (rate limiting) en todos los endpoints de la API. Considerar límites en la paginación, el tamaño de las respuestas y el uso de la CPU/memoria por solicitud. Implementar timeouts en las solicitudes.',
    mitigation_en: 'Implement rate limiting on all API endpoints. Consider limits on pagination, response sizes, and CPU/memory usage per request. Implement request timeouts.',
    tags: ['API Security', 'OWASP API Top 10'],
    reference: 'CWE-770'
  },
  {
    id: 'vuln-129',
    title_es: 'IDOR (Insecure Direct Object Reference)',
    title_en: 'IDOR (Insecure Direct Object Reference)',
    cvss: 8.8,
    severity: 'High',
    description_es: 'IDOR es un tipo de fallo de control de acceso donde la aplicación expone una referencia directa a un objeto interno (como un ID de base de datos) y no verifica si el usuario actual está autorizado para acceder a ese objeto. Un atacante puede manipular estos IDs para acceder a datos de otros usuarios.',
    description_en: 'IDOR is a type of access control failure where the application exposes a direct reference to an internal object (like a database ID) and fails to check if the current user is authorized to access that object. An attacker can manipulate these IDs to access other users\' data.',
    mitigation_es: 'Implementar una comprobación de control de acceso en el lado del servidor para cada solicitud que accede a un objeto de datos. Verificar que el usuario autenticado tiene permisos para acceder al objeto solicitado específico. Evitar el uso de IDs secuenciales y predecibles.',
    mitigation_en: 'Implement a server-side access control check for every request that accesses a data object. Verify that the authenticated user has permissions to access the specific requested object. Avoid using sequential and predictable IDs.',
    tags: ['OWASP Top 10', 'A01:2021-Broken Access Control'],
    reference: 'CWE-639'
  },
  {
    id: 'vuln-130',
    title_es: 'Fuga de Claves de API en Código Cliente',
    title_en: 'API Key Leakage in Client-Side Code',
    cvss: 6.5,
    severity: 'Medium',
    description_es: 'Una clave de API secreta está incrustada directamente en el código JavaScript del lado del cliente. Cualquier persona que inspeccione el código fuente de la página puede encontrar y robar esta clave, y luego usarla para abusar del servicio de terceros asociado.',
    description_en: 'A secret API key is embedded directly in the client-side JavaScript code. anyone who inspects the page\'s source code can find and steal this key, and then use it to abuse the associated third-party service.',
    mitigation_es: 'Nunca almacenar claves de API secretas en el código del lado del cliente. En su lugar, las solicitudes a la API de terceros deben ser realizadas a través de un backend propio que actúe como proxy. El backend puede almacenar la clave de forma segura y añadirla a las solicitudes salientes.',
    mitigation_en: 'Never store secret API keys in client-side code. Instead, requests to the third-party API should be made through a self-owned backend that acts as a proxy. The backend can securely store the key and add it to outgoing requests.',
    tags: ['Information Disclosure'],
    reference: 'CWE-798'
  },
  {
    id: 'vuln-131',
    title_es: 'Uso de `target="_blank"` sin `rel="noopener"`',
    title_en: 'Use of `target="_blank"` without `rel="noopener"`',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'Los enlaces que usan `target="_blank"` para abrir una nueva pestaña permiten que la nueva página tenga control parcial sobre la página original a través del objeto `window.opener`. Un atacante podría cambiar la página original a una de phishing.',
    description_en: 'Links that use `target="_blank"` to open a new tab allow the new page to have partial control over the original page through the `window.opener` object. An attacker could change the original page to a phishing site.',
    mitigation_es: 'Añadir siempre `rel="noopener"` (y opcionalmente `noreferrer`) a todos los enlaces que utilicen `target="_blank"`. Esto previene que la nueva página pueda acceder al `window.opener` de la página original.',
    mitigation_en: 'Always add `rel="noopener"` (and optionally `noreferrer`) to all links that use `target="_blank"`. This prevents the new page from accessing the original page\'s `window.opener`.',
    tags: ['Security Misconfiguration'],
    reference: 'CWE-1022'
  },
  {
    id: 'vuln-132',
    title_es: 'Respuestas de API sin Cache-Control o Pragma',
    title_en: 'API Responses without Cache-Control or Pragma',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'Las respuestas de API que contienen datos sensibles no incluyen cabeceras de control de caché (`Cache-Control: no-store, no-cache`, `Pragma: no-cache`). Esto podría permitir que un proxy o el navegador almacenen en caché estos datos, exponiéndolos a otros usuarios en una máquina compartida.',
    description_en: 'API responses containing sensitive data do not include cache control headers (`Cache-Control: no-store, no-cache`, `Pragma: no-cache`). This could allow a proxy or the browser to cache this data, exposing it to other users on a shared machine.',
    mitigation_es: 'Añadir las cabeceras `Cache-Control: no-store, no-cache, must-revalidate` y `Pragma: no-cache` a todas las respuestas de API que devuelvan información sensible.',
    mitigation_en: 'Add the headers `Cache-Control: no-store, no-cache, must-revalidate` and `Pragma: no-cache` to all API responses that return sensitive information.',
    tags: ['Information Disclosure'],
    reference: 'CWE-524'
  },
  {
    id: 'vuln-133',
    title_es: 'Inyección de CRLF',
    title_en: 'CRLF Injection',
    cvss: 6.1,
    severity: 'Medium',
    description_es: 'La inyección de CRLF ocurre cuando un atacante puede inyectar una secuencia de caracteres de "Retorno de Carro" y "Salto de Línea" (CRLF) en una respuesta HTTP. Esto puede llevar a la división de la respuesta HTTP (HTTP Response Splitting), permitiendo ataques como XSS o envenenamiento de caché.',
    description_en: 'CRLF injection occurs when an attacker can inject a sequence of "Carriage Return" and "Line Feed" (CRLF) characters into an HTTP response. This can lead to HTTP Response Splitting, allowing attacks like XSS or cache poisoning.',
    mitigation_es: 'Sanear toda la entrada del usuario que se vaya a incluir en las cabeceras de respuesta HTTP, eliminando los caracteres de nueva línea y retorno de carro (%0d, %0a).',
    mitigation_en: 'Sanitize all user input that will be included in HTTP response headers, removing newline and carriage return characters (%0d, %0a).',
    tags: ['Injection'],
    reference: 'CWE-93'
  },
  {
    id: 'vuln-134',
    title_es: 'Falta de HSTS (HTTP Strict Transport Security)',
    title_en: 'Missing HSTS (HTTP Strict Transport Security)',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La aplicación no utiliza la cabecera HSTS. Esto la hace vulnerable a ataques de "man-in-the-middle" como el SSL Stripping, donde un atacante puede degradar la conexión de HTTPS a HTTP para interceptar el tráfico.',
    description_en: 'The application does not use the HSTS header. This makes it vulnerable to man-in-the-middle attacks like SSL Stripping, where an attacker can downgrade the connection from HTTPS to HTTP to intercept traffic.',
    mitigation_es: 'Implementar la cabecera `Strict-Transport-Security` con un `max-age` largo (p. ej., 1 año) y la directiva `includeSubDomains`. Considerar añadir el dominio a la lista de precarga de HSTS.',
    mitigation_en: 'Implement the `Strict-Transport-Security` header with a long `max-age` (e.g., 1 year) and the `includeSubDomains` directive. Consider adding the domain to the HSTS preload list.',
    tags: ['Security Misconfiguration'],
    reference: 'CWE-319'
  },
  {
    id: 'vuln-135',
    title_es: 'Uso de Funciones Aleatorias Inseguras para Fines Criptográficos',
    title_en: 'Use of Insecure Random Functions for Cryptographic Purposes',
    cvss: 5.9,
    severity: 'Medium',
    description_es: 'La aplicación utiliza generadores de números pseudo-aleatorios (PRNG) no criptográficamente seguros (como `Math.random` o `rand()`) para generar valores que deben ser impredecibles, como tokens de sesión, tokens CSRF o URLs para restablecer contraseñas.',
    description_en: 'The application uses non-cryptographically secure pseudo-random number generators (PRNGs) (like `Math.random` or `rand()`) to generate values that should be unpredictable, such as session tokens, CSRF tokens, or password reset URLs.',
    mitigation_es: 'Utilizar siempre un generador de números aleatorios criptográficamente seguro (CSPRNG) proporcionado por el sistema operativo o un framework seguro para generar todos los valores sensibles a la seguridad.',
    mitigation_en: 'Always use a cryptographically secure pseudo-random number generator (CSPRNG) provided by the operating system or a secure framework to generate all security-sensitive values.',
    tags: ['Cryptographic Failures'],
    reference: 'CWE-338'
  },
  {
    id: 'vuln-136',
    title_es: 'Exposición de Archivos de Backup',
    title_en: 'Backup File Exposure',
    cvss: 7.5,
    severity: 'High',
    description_es: 'Archivos de backup (p. ej., `config.php.bak`, `database.sql`) son accesibles públicamente en el servidor web. Estos archivos a menudo contienen código fuente, credenciales de base de datos u otra información sensible.',
    description_en: 'Backup files (e.g., `config.php.bak`, `database.sql`) are publicly accessible on the web server. These files often contain source code, database credentials, or other sensitive information.',
    mitigation_es: 'Asegurarse de que el proceso de despliegue elimine cualquier archivo de backup. Configurar el servidor web para denegar el acceso a extensiones de archivo comunes de backups (.bak, .old, .sql, .zip, etc.). Almacenar los backups en un lugar seguro fuera del directorio raíz web.',
    mitigation_en: 'Ensure the deployment process removes any backup files. Configure the web server to deny access to common backup file extensions (.bak, .old, .sql, .zip, etc.). Store backups in a secure location outside the web root directory.',
    tags: ['Information Disclosure'],
    reference: 'CWE-530'
  },
  {
    id: 'vuln-137',
    title_es: 'Exposición de Endpoints de Debug/Test en Producción',
    title_en: 'Exposure of Debug/Test Endpoints in Production',
    cvss: 6.5,
    severity: 'Medium',
    description_es: 'Endpoints o funcionalidades que se usaron para depuración o pruebas durante el desarrollo (p. ej., `/debug`, `/test_db_reset`) se han dejado habilitados en el entorno de producción. Estos pueden exponer información sensible o permitir acciones destructivas.',
    description_en: 'Endpoints or features used for debugging or testing during development (e.g., `/debug`, `/test_db_reset`) have been left enabled in the production environment. These can expose sensitive information or allow destructive actions.',
    mitigation_es: 'Utilizar flags de compilación o variables de entorno para deshabilitar completamente el código y los endpoints de depuración en las builds de producción. Implementar un proceso de revisión antes del despliegue para asegurar que no se incluye código de prueba.',
    mitigation_en: 'Use build flags or environment variables to completely disable debug code and endpoints in production builds. Implement a pre-deployment review process to ensure no test code is included.',
    tags: ['Security Misconfiguration'],
    reference: 'CWE-489'
  },
  {
    id: 'vuln-138',
    title_es: 'Web Cache Deception',
    title_en: 'Web Cache Deception',
    cvss: 7.5,
    severity: 'High',
    description_es: 'Un atacante engaña a un servidor de caché web para que almacene incorrectamente contenido privado de un usuario y lo sirva a otros usuarios. Esto ocurre cuando la aplicación permite rutas de archivo flexibles y un servidor de caché está configurado para almacenar en caché archivos basándose en la extensión.',
    description_en: 'An attacker tricks a web cache server into incorrectly storing a user\'s private content and serving it to other users. This occurs when the application allows flexible file paths and a cache server is configured to cache files based on extension.',
    mitigation_es: 'Configurar el servidor de caché para que no almacene en caché páginas que no debería. La solución más robusta es no permitir que la entrada del usuario defina rutas que parezcan archivos estáticos. Configurar la aplicación para que responda con 404 a rutas inválidas.',
    mitigation_en: 'Configure the cache server not to cache pages it shouldn\'t. The most robust solution is not to allow user input to define paths that look like static files. Configure the application to respond with a 404 to invalid paths.',
    tags: ['Cache Poisoning'],
    reference: 'CWE-445'
  },
  {
    id: 'vuln-139',
    title_es: 'Password in URL',
    title_en: 'Password in URL',
    cvss: 6.5,
    severity: 'Medium',
    description_es: 'La aplicación transmite contraseñas u otros secretos como parámetros en la URL. Las URLs se almacenan en el historial del navegador, en los logs del servidor web, en los logs de proxies, y pueden ser vistas por encima del hombro o compartidas accidentalmente, exponiendo la credencial.',
    description_en: 'The application transmits passwords or other secrets as parameters in the URL. URLs are stored in browser history, web server logs, proxy logs, and can be seen over the shoulder or accidentally shared, exposing the credential.',
    mitigation_es: 'Nunca transmitir información sensible en los parámetros de la URL. Utilizar siempre el cuerpo de una solicitud POST para enviar credenciales y otros secretos.',
    mitigation_en: 'Never transmit sensitive information in URL parameters. Always use the body of a POST request to send credentials and other secrets.',
    tags: ['Information Disclosure'],
    reference: 'CWE-598'
  },
  {
    id: 'vuln-140',
    title_es: 'Falta de Protección contra el Tabnabbing',
    title_en: 'Missing Tabnabbing Protection',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'Similar a la vulnerabilidad de `target="_blank"`, pero el ataque se centra en cambiar la pestaña original a un sitio de phishing cuando el usuario no está mirando. Si un enlace abre una nueva pestaña, la nueva página puede cambiar la ubicación de la página original.',
    description_en: 'Similar to the `target="_blank"` vulnerability, but the attack focuses on changing the original tab to a phishing site when the user is not looking. If a link opens a new tab, the new page can change the location of the original page.',
    mitigation_es: 'Añadir el atributo `rel="noopener noreferrer"` a todos los enlaces que se abren en una nueva pestaña o ventana.',
    mitigation_en: 'Add the `rel="noopener noreferrer"` attribute to all links that open in a new tab or window.',
    tags: ['Phishing'],
    reference: 'CWE-1022'
  },
  {
    id: 'vuln-141',
    title_es: 'Uso de Cookies Persistentes para Información Sensible',
    title_en: 'Use of Persistent Cookies for Sensitive Information',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La aplicación utiliza cookies persistentes (con una fecha de caducidad) para almacenar información sensible, como los IDs de sesión. Si un atacante obtiene acceso a la máquina de la víctima, puede robar estas cookies del disco y reutilizarlas, incluso después de que el navegador se haya cerrado.',
    description_en: 'The application uses persistent cookies (with an expiration date) to store sensitive information, such as session IDs. If an attacker gains access to the victim\'s machine, they can steal these cookies from the disk and reuse them, even after the browser has been closed.',
    mitigation_es: 'Utilizar cookies de sesión (no persistentes) para toda la información sensible. Estas cookies se eliminan cuando se cierra el navegador. Si se requiere la funcionalidad "recordarme", implementar una solución más segura basada en tokens.',
    mitigation_en: 'Use session cookies (non-persistent) for all sensitive information. These cookies are deleted when the browser is closed. If "remember me" functionality is required, implement a more secure token-based solution.',
    tags: ['Session Management'],
    reference: 'CWE-539'
  },
  {
    id: 'vuln-142',
    title_es: 'Falta de Confirmación para Acciones Sensibles',
    title_en: 'Missing Confirmation for Sensitive Actions',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'La aplicación permite realizar acciones sensibles (como eliminar una cuenta, cambiar el correo electrónico o la contraseña) sin requerir que el usuario vuelva a introducir su contraseña actual o confirme la acción a través de un segundo factor (como un código por correo electrónico).',
    description_en: 'The application allows sensitive actions (such as deleting an account, changing email or password) to be performed without requiring the user to re-enter their current password or confirm the action via a second factor (like an email code).',
    mitigation_es: 'Requerir que el usuario proporcione su contraseña actual antes de permitir cualquier cambio en la configuración de seguridad de la cuenta o la eliminación de la misma. Considerar la verificación por correo electrónico para cambios críticos.',
    mitigation_en: 'Require the user to provide their current password before allowing any changes to the account\'s security settings or its deletion. Consider email verification for critical changes.',
    tags: ['Authentication'],
    reference: 'CWE-305'
  },
  {
    id: 'vuln-143',
    title_es: 'Fijación de Sesión (Session Fixation)',
    title_en: 'Session Fixation',
    cvss: 8.8,
    severity: 'High',
    description_es: 'La fijación de sesión es un ataque que permite a un atacante fijar el ID de sesión de una víctima. Después de que el ID de sesión ha sido fijado, el atacante espera a que la víctima inicie sesión, y una vez que lo hace, el atacante puede usar el mismo ID para hacerse pasar por la víctima.',
    description_en: 'Session fixation is an attack that permits an attacker to fixate a victim\'s session ID. After a session ID has been fixated, the attacker waits for the victim to log in, and once they do, the attacker can use the same ID to impersonate the victim.',
    mitigation_es: 'Regenerar el ID de sesión inmediatamente después de una autenticación exitosa. No aceptar IDs de sesión de los parámetros de la URL.',
    mitigation_en: 'Regenerate the session ID immediately after successful authentication. Do not accept session IDs from URL parameters.',
    tags: ['Session Management'],
    reference: 'CWE-384'
  },
  {
    id: 'vuln-144',
    title_es: 'Cross-Site Script Inclusion (XSSI)',
    title_en: 'Cross-Site Script Inclusion (XSSI)',
    cvss: 6.5,
    severity: 'Medium',
    description_es: 'XSSI es un tipo de vulnerabilidad que permite a un sitio web malicioso incluir un script de otro dominio para leer datos que contiene. A diferencia de XSS, no requiere inyectar script en el sitio vulnerable, sino aprovechar la capacidad de los navegadores de incluir scripts de cualquier origen.',
    description_en: 'XSSI is a type of vulnerability that allows a malicious website to include a script from another domain to read data it contains. Unlike XSS, it does not require injecting a script into the vulnerable site, but rather leveraging the browser\'s ability to include scripts from any origin.',
    mitigation_es: 'No envolver datos sensibles JSON en llamadas a funciones (JSONP) si no es estrictamente necesario. Si se usa JSONP, asegurarse de que no se puedan adivinar los nombres de las funciones. Como defensa general, devolver datos sensibles solo en respuestas POST o proteger los endpoints con tokens anti-CSRF.',
    mitigation_en: 'Do not wrap sensitive JSON data in function calls (JSONP) unless strictly necessary. If JSONP is used, ensure function names cannot be guessed. As a general defense, return sensitive data only in POST responses or protect endpoints with anti-CSRF tokens.',
    tags: ['XSSI'],
    reference: 'CWE-200'
  },
  {
    id: 'vuln-145',
    title_es: 'Falta de Sandbox en iframes',
    title_en: 'Missing Sandbox Attribute in iframes',
    cvss: 5.3,
    severity: 'Medium',
    description_es: 'La aplicación utiliza iframes para mostrar contenido de terceros o no confiable sin utilizar el atributo `sandbox`. Esto permite que el contenido del iframe ejecute scripts, envíe formularios, o navegue por la página principal, lo que puede llevar a ataques de phishing o XSS.',
    description_en: 'The application uses iframes to display third-party or untrusted content without using the `sandbox` attribute. This allows the iframe content to execute scripts, submit forms, or navigate the top-level page, which can lead to phishing or XSS attacks.',
    mitigation_es: 'Añadir el atributo `sandbox` a todos los iframes que carguen contenido no confiable. Configurar las directivas del sandbox (`allow-scripts`, `allow-same-origin`, etc.) con el mínimo de permisos necesarios para que el contenido funcione.',
    mitigation_en: 'Add the `sandbox` attribute to all iframes that load untrusted content. Configure the sandbox directives (`allow-scripts`, `allow-same-origin`, etc.) with the minimum permissions necessary for the content to function.',
    tags: ['Security Misconfiguration'],
    reference: 'CWE-1021'
  },
  {
    id: 'vuln-146',
    title_es: 'Inyección de Email Header',
    title_en: 'Email Header Injection',
    cvss: 6.1,
    severity: 'Medium',
    description_es: 'Si la entrada del usuario se utiliza para construir las cabeceras de un correo electrónico (como el campo `Subject` o `To`), un atacante puede inyectar caracteres de nueva línea para añadir cabeceras adicionales (como `Bcc`) y usar la aplicación para enviar spam de forma anónima.',
    description_en: 'If user input is used to construct email headers (such as the `Subject` or `To` field), an attacker can inject newline characters to add additional headers (like `Bcc`) and use the application to send spam anonymously.',
    mitigation_es: 'Sanear toda la entrada del usuario que se vaya a utilizar en las cabeceras de los correos electrónicos, eliminando cualquier carácter de nueva línea o retorno de carro. Utilizar librerías de correo seguras que manejen esto automáticamente.',
    mitigation_en: 'Sanitize all user input that will be used in email headers, removing any newline or carriage return characters. Use secure mail libraries that handle this automatically.',
    tags: ['Injection'],
    reference: 'CWE-93'
  },
  {
    id: 'vuln-147',
    title_es: 'Ataque de Repetición (Replay Attack)',
    title_en: 'Replay Attack',
    cvss: 6.5,
    severity: 'Medium',
    description_es: 'Un atacante captura una solicitud de red válida y la reenvía para realizar una acción maliciosa. Por ejemplo, si una solicitud para transferir dinero no tiene una protección única, un atacante podría repetirla para transferir dinero varias veces.',
    description_en: 'An attacker captures a valid network request and resends it to perform a malicious action. For example, if a request to transfer money does not have a unique protection, an attacker could replay it to transfer money multiple times.',
    mitigation_es: 'Implementar un "nonce" (número usado una sola vez) en todas las solicitudes que realizan cambios de estado. El servidor debe registrar los nonces utilizados y rechazar cualquier solicitud que contenga un nonce repetido.',
    mitigation_en: 'Implement a "nonce" (number used once) in all state-changing requests. The server must record used nonces and reject any request containing a repeated nonce.',
    tags: ['Authentication'],
    reference: 'CWE-294'
  },
  {
    id: 'vuln-148',
    title_es: 'Exposición de Archivos de Configuración',
    title_en: 'Configuration File Exposure',
    cvss: 7.5,
    severity: 'High',
    description_es: 'Archivos de configuración sensibles como `web.config`, `.env`, o `appsettings.json` son accesibles públicamente. Estos archivos a menudo contienen cadenas de conexión a bases de datos, claves de API, y otros secretos.',
    description_en: 'Sensitive configuration files like `web.config`, `.env`, or `appsettings.json` are publicly accessible. These files often contain database connection strings, API keys, and other secrets.',
    mitigation_es: 'Mover los archivos de configuración fuera del directorio raíz web. Configurar el servidor web para denegar explícitamente el acceso a estos archivos y sus extensiones.',
    mitigation_en: 'Move configuration files outside the web root directory. Configure the web server to explicitly deny access to these files and their extensions.',
    tags: ['Information Disclosure'],
    reference: 'CWE-548'
  },
  {
    id: 'vuln-149',
    title_es: 'Contenido Mixto (Mixed Content)',
    title_en: 'Mixed Content',
    cvss: 4.3,
    severity: 'Medium',
    description_es: 'Una página HTTPS carga recursos (como scripts o imágenes) a través de HTTP. Esto debilita la seguridad de la página, ya que un atacante en la red podría interceptar y modificar el contenido HTTP, potencialmente inyectando scripts maliciosos.',
    description_en: 'An HTTPS page loads resources (like scripts or images) over HTTP. This weakens the security of the page, as an attacker on the network could intercept and modify the HTTP content, potentially injecting malicious scripts.',
    mitigation_es: 'Asegurarse de que todos los recursos se carguen a través de HTTPS. Utilizar la directiva `upgrade-insecure-requests` en la Content-Security-Policy (CSP) para pedir al navegador que intente actualizar las solicitudes HTTP a HTTPS.',
    mitigation_en: 'Ensure all resources are loaded over HTTPS. Use the `upgrade-insecure-requests` directive in the Content-Security-Policy (CSP) to ask the browser to attempt to upgrade HTTP requests to HTTPS.',
    tags: ['Security Misconfiguration'],
    reference: 'CWE-311'
  },
  {
    id: 'vuln-150',
    title_es: 'Contraseñas Almacenadas en Texto Plano',
    title_en: 'Passwords Stored in Plaintext',
    cvss: 9.8,
    severity: 'Critical',
    description_es: 'Las contraseñas de los usuarios se almacenan en la base de datos en texto plano o con un cifrado reversible. Si la base de datos se ve comprometida, todas las contraseñas de los usuarios quedarán expuestas inmediatamente.',
    description_en: 'User passwords are stored in the database in plaintext or with reversible encryption. If the database is compromised, all user passwords will be immediately exposed.',
    mitigation_es: 'Nunca almacenar contraseñas en texto plano. Utilizar siempre funciones de hashing de contraseñas fuertes, lentas y con sal (como Argon2, scrypt, bcrypt) para almacenar los hashes de las contraseñas.',
    mitigation_en: 'Never store passwords in plaintext. Always use strong, slow, salted password hashing functions (like Argon2, scrypt, bcrypt) to store password hashes.',
    tags: ['Cryptographic Failures'],
    reference: 'CWE-257'
  }
];
