export {
  WarningCircle as AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowsDownUp as ArrowUpDown,
  Medal as Award,
  TextB as Bold,
  Bomb,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarIcon,
  Check,
  CheckCircle,
  CheckSquare,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUpDown as ChevronsUpDown,
  CaretUp as ChevronUp,
  Circle,
  Code,
  Copy,
  PencilSimple as Edit,
  Eye,
  EyeSlash as EyeOff,
  File,
  FileCode,
  FileArrowDown as FileDown,
  FilePlus as FilePlus2,
  FileText,
  FileArrowUp as FileUp,
  Kanban as FolderKanban,
  Images as GalleryHorizontal,
  Globe,
  DotsSixVertical as GripVertical,
  TextHOne as Heading1,
  TextHTwo as Heading2,
  TextHThree as Heading3,
  TextHFour as Heading4,
  ClockCounterClockwise as History,
  House as Home,
  Image,
  Image as ImageIcon,
  TextItalic as Italic,
  Key as KeyRound,
  Translate as Languages,
  Layout as LayoutTemplate,
  Link,
  List,
  ListBullets,
  ListNumbers,
  ListNumbers as ListOrdered,
  Minus,
  Moon,
  Network,
  Sidebar as PanelLeft,
  Plus,
  PlusCircle,
  Printer,
  Quotes as Quote,
  Rows,
  FloppyDisk as Save,
  Scan,
  MagnifyingGlass as Search,
  Gear as Settings,
  ShieldCheck,
  Shield as ShieldHalf,
  DeviceMobile as Smartphone,
  TextStrikethrough as Strikethrough,
  Sun,
  Table,
  TextT as Text,
  Trash as Trash2,
  Upload,
  User,
  Users,
  WifiHigh as Wifi,
  TextAlignLeft as WrapText,
  X,
} from '@phosphor-icons/react/dist/ssr';
